# Build settings
permalink   : /blog/:year/:title/
markdown    : kramdown
highlighter : rouge
gems: [jekyll-paginate]

paginate: 3
paginate_path: "/blog/page/:num/"
comments: true

source: source
destination: _site
sass:
  sass_dir: _scss
  style: compressed # expanded

# SEO settings
title: Raghavendra
description: "Raghavendra Ravikumar or Raghavendra Gujar is an Engineer who is currently working on the Front End of Web Applications. He is passionate about bringing new ideas to life. He believes knowledge can be gained and enhanced through the process of learning and teaching."
keywords: "Javascript, HTML, CSS, UI"
url: https://raghavgujjar.github.io
baseurl: ""
# baseurl: ""

google_analytics: UA-78703207-1
repo: http://github.com/raghavgujjar/raghavgujjar.github.io
disqus_shortname: "raghavgujjar"
disqus_site_shortname: "raghavgujjar"

# Author settings
author:
  name      : Raghavendra
  job       : Engineer
  tagline   : "Knowledge = Learn + Teach"
  thumb     : /images/author.jpg
  email     : raghavendra.ravikumar@gmail.com
  url       : https://raghavgujjar.github.io
  github    : http://github.com/raghavgujjar
  twitter   : https://twitter.com/r2_g1
  contact   : https://docs.google.com/forms/d/1kHrmM-W-ICc6elHCWZIIK3tH-Be0McAuGFGCpl23WNg/viewform
  #facebook  :
  #linkedin  :

# navbar pages
navbar:
  - slug: about
    title: About
  # - slug: resume
  #   title: Resume
  # - slug: skills
  #   title: Skills
  - slug: blog
    title: Blog

exclude: ["gulp", "node_modules", "bower", "bower_components", "config.rb", "src", "Gemfile", "Gemfile.lock", ".rvmrc", ".rbenv-version", "package.json", "gulpfile.js", "README.md", "Rakefile", "changelog.md"]
